import type { Metadata } from "next"
import "./globals.css"
import { geistMono, geistSans, poppins } from "./fonts"
import { TooltipProvider } from "@/components/ui/tooltip"
import ToastifyProvider from "@/providers/ToastifyProvider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
        <TooltipProvider>
          <ToastifyProvider>{children}</ToastifyProvider>
        </TooltipProvider>
      </body>
    </html>
  )
}
